// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6I24oUkNB0AQsmOpGq5n-sMtNHkCENVM',
    appId: '1:1063091594215:web:e6806779d2ec60d5239342',
    messagingSenderId: '1063091594215',
    projectId: 'bynry-cca95',
    authDomain: 'bynry-cca95.firebaseapp.com',
    storageBucket: 'bynry-cca95.appspot.com',
    measurementId: 'G-TL75NRH19X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFxmqSMf9MIULITzkPjudxX-Gs1MKyxYg',
    appId: '1:1063091594215:android:c90c9582e3166953239342',
    messagingSenderId: '1063091594215',
    projectId: 'bynry-cca95',
    storageBucket: 'bynry-cca95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfLpXpQqJqyC3raTUtPCe2Ur4GM8Rduo',
    appId: '1:1063091594215:ios:cb9d6a26c21dd73c239342',
    messagingSenderId: '1063091594215',
    projectId: 'bynry-cca95',
    storageBucket: 'bynry-cca95.appspot.com',
    iosBundleId: 'com.example.flutterSinging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfLpXpQqJqyC3raTUtPCe2Ur4GM8Rduo',
    appId: '1:1063091594215:ios:cb9d6a26c21dd73c239342',
    messagingSenderId: '1063091594215',
    projectId: 'bynry-cca95',
    storageBucket: 'bynry-cca95.appspot.com',
    iosBundleId: 'com.example.flutterSinging',
  );
}
